/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_agora_tutorials1v1acall_VoiceChatViewActivity */

#ifndef _Included_io_agora_tutorials1v1acall_VoiceChatViewActivity
#define _Included_io_agora_tutorials1v1acall_VoiceChatViewActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef io_agora_tutorials1v1acall_VoiceChatViewActivity_PERMISSION_REQ_ID
#define io_agora_tutorials1v1acall_VoiceChatViewActivity_PERMISSION_REQ_ID 22L
/*
 * Class:     io_agora_tutorials1v1acall_VoiceChatViewActivity
 * Method:    pushAudioData
 * Signature: ([BIII)V
 */
JNIEXPORT void JNICALL Java_io_agora_tutorials1v1acall_VoiceChatViewActivity_pushAudioData
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
