/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_agora_tutorials1v1acall_VoiceChatViewActivity */

#ifndef _Included_io_agora_tutorials1v1acall_VoiceChatViewActivity
#define _Included_io_agora_tutorials1v1acall_VoiceChatViewActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef io_agora_tutorials1v1acall_VoiceChatViewActivity_PERMISSION_REQ_ID
#define io_agora_tutorials1v1acall_VoiceChatViewActivity_PERMISSION_REQ_ID 22L
#undef io_agora_tutorials1v1acall_VoiceChatViewActivity_BEDEBUG
#define io_agora_tutorials1v1acall_VoiceChatViewActivity_BEDEBUG 0L
#undef io_agora_tutorials1v1acall_VoiceChatViewActivity_CHANNELS
#define io_agora_tutorials1v1acall_VoiceChatViewActivity_CHANNELS 2L
#undef io_agora_tutorials1v1acall_VoiceChatViewActivity_SAMPLESPERCELL
#define io_agora_tutorials1v1acall_VoiceChatViewActivity_SAMPLESPERCELL 960L
/*
 * Class:     io_agora_tutorials1v1acall_VoiceChatViewActivity
 * Method:    enableAudioPreProcessing
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_io_agora_tutorials1v1acall_VoiceChatViewActivity_enableAudioPreProcessing
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     io_agora_tutorials1v1acall_VoiceChatViewActivity
 * Method:    audioDataPara
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_io_agora_tutorials1v1acall_VoiceChatViewActivity_audioDataPara
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
